### ISSUE TITLE
Textura costillas

### ISSUE THREAD

**Issue by jhordanres** [gislersoft/quoragame#19]
<b>Las costillas del terreno no se le asignan las texturas </b>

**Comment by jhordanres** [comment]
![bug_costilla](https://user-images.githubusercontent.com/32309401/36635391-fcf90890-1981-11e8-9507-97b77fd6af5e.png)

**Comment by jhordanres** [comment]
resuelto en https://github.com/gislersoft/quoragame/pull/23

**Comment by gislersoft** [comment]
merged
