### ISSUE TITLE
La animación de la puerta de entrada

### ISSUE THREAD

**Issue by Felipe960112** [gislersoft/quoragame#25]
La animación de la puerta de entrada, desde adentro, muestra un error de textura

**Comment by gislersoft** [comment]
![defecto](https://user-images.githubusercontent.com/9287467/45921900-a3ed5280-be84-11e8-81fe-18a04d86faf8.png)

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/74

**Comment by gislersoft** [comment]
@sebastianq96  Te falta actualizar la escena porque las puertas que estan asociadas en la base militar son las del prefab, actualiza este PR enviando la escena en este caso te toca hacer lo que haria el level designer, luego de que hagas eso prueba que sigue funcionando.

**Comment by gislersoft** [comment]
![puertasobrepuesta](https://user-images.githubusercontent.com/9287467/46225581-5870f380-c31f-11e8-938d-963b8a56cd28.png)
El PR que enviaste aun tiene problemas con la puerta, por favor verificar que no se salga la puerta cuando abre.

**Comment by gislersoft** [comment]
5
