### ISSUE TITLE
Hongo Sin Esporas

### ISSUE THREAD

**Issue by Dalox** [gislersoft/quoragame#60]
![image](https://user-images.githubusercontent.com/22529648/45921924-342b9780-be85-11e8-84bc-3db9af0a415b.png)

Hay un Hongo que le faltan el lanzamiento de esporas

**Comment by gislersoft** [comment]
Sugiero modificar únicamente el prefab si existe el prefab no recuerdo si quedo el prefab o no, este issue requiere probablemente tocar la escena sugiero estar pendiente de otros PR´s que van a tocar la escena porque se te puede presentar un conflicto.

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/76

**Comment by gislersoft** [comment]
5
