### ISSUE TITLE
HUD no tiene barra de vida

### ISSUE THREAD

**Issue by alejandro1214** [gislersoft/quoragame#61]
El personaje no posee HUD de vida 
![hub](https://user-images.githubusercontent.com/41840097/45921925-40aff000-be85-11e8-930c-1edcceb861b0.png)

**Comment by gislersoft** [comment]
![screen shot 2018-09-26 at 9 41 42 am](https://user-images.githubusercontent.com/9287467/46087689-806e2480-c170-11e8-9fea-19c8236884fa.png)
Trata de que sea algo simple cómo esto, debe reflejar el valor real de vida no solamente una imagen, pero tampoco se debe desarrollar lo que puede herir al personaje, la idea es que se pueda modificar un valor numerico en el inspector y que la barra refleje este valor.

**Comment by VVO2018** [comment]
Profe, no me permite hacer el Pull Request.
![captura](https://user-images.githubusercontent.com/41840326/46237581-ffb75000-c34a-11e8-9817-3efff6c89629.PNG)

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/85
