### ISSUE TITLE
Sin colisiones

### ISSUE THREAD

**Issue by Dalox** [gislersoft/quoragame#63]
![image](https://user-images.githubusercontent.com/22529648/45921938-78b73300-be85-11e8-9986-9589c79d84bc.png)

Hay alguno objetos que se pueden atravesar de ellos como la flora y los huesos.

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/issues/67

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/issues/69

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/issues/70

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/75

**Comment by gislersoft** [comment]
solucionado por otro usuario.
