### ISSUE TITLE
Problema con el elevador

### ISSUE THREAD

**Issue by catv98** [gislersoft/quoragame#64]
No existe dispositivo para que el elevador suba o baje

**Comment by catv98** [comment]
![error elevador](https://user-images.githubusercontent.com/30535075/45921954-c0d65580-be85-11e8-9f09-08e13b6a5228.png)

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/commit/12413034ff575d5650107d5b6f472d1f441fe764 Resuelto en este commit.
