### ISSUE TITLE
Altura del personaje

### ISSUE THREAD

**Issue by Dalox** [gislersoft/quoragame#65]
![image](https://user-images.githubusercontent.com/22529648/45921950-b2883980-be85-11e8-92f8-6038a17efc10.png)

En el videojuego, la altura del personaje no es proporcional a mucho objetos interactivos del juego. ajustar la altura de la camara.

**Comment by gislersoft** [comment]
En este caso se debe verificar el capsule collider que tiene asociado el personaje, y realizar pruebas que luego de modificar la altura no se atasque en lugares donde no se debería atascar, la solución a este issue no debe modificar el entorno solo el collider.

**Comment by breyneralbarracin** [comment]
Existen elementos que no están escalados correctamente, debido a eso, escalar el personaje afecta ligeramente como se percibe el mundo donde se encuentra, mas puntualmente se ve lo siguiente en relación a la base:

![base1](https://user-images.githubusercontent.com/42898778/46233074-ffad5500-c336-11e8-940d-b0e2f91965dc.PNG)
![base2](https://user-images.githubusercontent.com/42898778/46233076-01771880-c337-11e8-8c57-5300b8d89b51.PNG)

Se aprecia una relación un tanto extraña entre la base y el personaje; sin embargo se ajusto para coincidir con el botón del ascensor y algunos otros elementos como los huesos y los hongos:

![bug2](https://user-images.githubusercontent.com/42898778/46233110-1eabe700-c337-11e8-97b7-1974bc0ab185.png)

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/78

**Comment by gislersoft** [comment]
Falta subir el cambio en la escena solo quedo actualizado el prefab

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/78

**Comment by gislersoft** [comment]
5
