### ISSUE TITLE
Retraso en el Cañon

### ISSUE THREAD

**Issue by Dalox** [gislersoft/quoragame#71]
![image](https://user-images.githubusercontent.com/22529648/45921970-32ae9f00-be86-11e8-8ef5-43a2e18b555e.png)

Revisar la velocidad de disparo y la velocidad del projectil devido a que se complica el esquivarlo.

**Comment by gislersoft** [comment]
Yo sugiero reducir el tiempo que actualmente tiene entre disparo y disparo más que la velocidad de la bala, lo importante es que una vez que esta bala pegue con el personaje le haga daño para eso debes estar pendiente de la solución de este "enhancement"  [https://github.com/gislersoft/quoragame/issues/61](https://github.com/gislersoft/quoragame/issues/61) por lo tanto tu PR depende de que ese este mezclado.

**Comment by acarcila** [comment]
@gislersoft hola profe, ya hice el pull request pero aun no estaba lo del enhancement #61 por lo tanto solo subí mi parte.

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/80

**Comment by gislersoft** [comment]
5
