### ISSUE TITLE
Falta de efecto en el choque del láser (enemigo)

### ISSUE THREAD

**Issue by breyneralbarracin** [gislersoft/quoragame#72]
El "ojo" (enemigo) lanza un rayo láser que al impactar desaparece sin mas, sería bueno colocar un efecto (posible explosión o efecto visual)

**Comment by gislersoft** [comment]
@Dalox Puedes solucionar este defecto mejor? el otro fue un error mio que borre un archivo que no era, trabaja mejor este.

**Comment by gislersoft** [comment]
https://github.com/gislersoft/quoragame/pull/81

**Comment by gislersoft** [comment]
5
